# Generated by Django 5.1.5 on 2025-01-24 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0006_documenttype_alter_document_document_type'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='required_documents',
            field=models.ManyToManyField(related_name='students', to='documents.documenttype'),
        ),
    ]
