# Generated by Django 5.1.5 on 2025-01-24 07:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_applicanttype'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='applicant_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='students.applicanttype'),
        ),
    ]
