# Generated by Django 5.1.5 on 2025-01-28 08:42

import django.db.models.deletion
import documents.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('학생생활기록부', '학생생활기록부'), ('검정고시합격증명서', '검정고시합격증명서'), ('생활기록부대체양식', '생활기록부대체양식'), ('기초생활수급자증명서', '기초생활수급자증명서'), ('주민등록본', '주민등록본'), ('국민체력100인증서', '국민체력100인증서'), ('체력평가', '체력평가'), ('논술', '논술'), ('알수없음', '알수없음')], default='알수없음', max_length=50)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('state', models.CharField(choices=[('미제출', '미제출'), ('검토', '검토'), ('제출', '제출')], default='미제출', max_length=10)),
                ('file_url', models.FileField(upload_to=documents.models.Document.upload_to)),
                ('criteria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aims.essaycriteria')),
            ],
        ),
    ]
