# Generated by Django 5.1.5 on 2025-01-19 07:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='memo',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='state',
            field=models.CharField(choices=[('미제출', '미제출'), ('검토', '검토'), ('제출', '제출')], default='미제출', max_length=10),
        ),
        migrations.AlterField(
            model_name='document',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='students.student'),
        ),
    ]
