# Generated by Django 5.1.5 on 2025-01-18 17:55

import documents.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file_url',
            field=models.FileField(upload_to=documents.models.Document.upload_to),
        ),
    ]
