# Generated by Django 5.1.5 on 2025-01-19 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_document_memo_document_state_alter_document_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='memo',
        ),
    ]
