# Generated by Django 5.1.5 on 2025-01-29 06:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_documentation'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentation',
            name='student_id',
            field=models.ForeignKey(default=20250000, on_delete=django.db.models.deletion.CASCADE, related_name='documentation', to='students.student'),
        ),
    ]
