# Generated by Django 5.1.5 on 2025-01-23 01:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aims', '0005_essaycriteria'),
        ('documents', '0003_remove_document_memo'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='criteria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aims.essaycriteria'),
        ),
    ]
