# Generated by Django 5.1.5 on 2025-01-31 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_alter_document_document_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document_type',
            field=models.CharField(choices=[('알수없음', '알수없음'), ('검정고시합격증명서', '검정고시합격증명서'), ('국민체력100인증서', '국민체력100인증서'), ('기초생활수급자증명서', '기초생활수급자증명서'), ('주민등록초본', '주민등록초본'), ('체력평가', '체력평가'), ('생활기록부대체양식', '생활기록부대체양식'), ('학생생활기록부', '학생생활기록부'), ('논술', '논술')], default='논술', max_length=50),
        ),
        migrations.AlterField(
            model_name='documentation',
            name='document_type',
            field=models.CharField(choices=[('알수없음', '알수없음'), ('검정고시합격증명서', '검정고시합격증명서'), ('국민체력100인증서', '국민체력100인증서'), ('기초생활수급자증명서', '기초생활수급자증명서'), ('주민등록초본', '주민등록초본'), ('체력평가', '체력평가'), ('생활기록부대체양식', '생활기록부대체양식'), ('학생생활기록부', '학생생활기록부'), ('논술', '논술')], default='알수없음', max_length=50),
        ),
    ]
