# Generated by Django 5.1.5 on 2025-01-24 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_alter_document_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AlterField(
            model_name='document',
            name='document_type',
            field=models.CharField(choices=[('학생생활기록부', '학생생활기록부'), ('검정고시합격증명서', '검정고시합격증명서'), ('생활기록부대체양식', '생활기록부대체양식'), ('기초생활수급자증명서', '기초생활수급자증명서'), ('주민등록본', '주민등록본'), ('국민체력100인증서', '국민체력100인증서'), ('체력평가', '체력평가'), ('논술', '논술')], max_length=50),
        ),
    ]
