# Generated by Django 5.1.5 on 2025-02-07 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0006_alter_document_document_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentation',
            name='issue_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
