# Generated by Django 5.1.5 on 2025-02-07 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0007_documentation_issue_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentation',
            name='confidence',
            field=models.FloatField(default=0.0),
        ),
    ]
