# Generated by Django 5.1.5 on 2025-01-27 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0008_alter_document_document_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ValidationCriteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(max_length=100)),
                ('v_condition', models.TextField()),
            ],
        ),
    ]
