# Generated by Django 5.1.5 on 2025-01-27 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0009_validationcriteria'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ValidationCriteria',
        ),
    ]
