# Generated by Django 5.1.5 on 2025-01-27 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0010_delete_validationcriteria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='state',
            field=models.CharField(choices=[('미제출', '미제출'), ('검토', '검토'), ('제출', '제출')], default='미제출', max_length=10),
        ),
    ]
