# aims/migrations/0001_initial.py

# Generated by Django 5.1.5 on 2025-01-28 08:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        
    ]

    operations = [
        # DocumentPassFail
        migrations.CreateModel(
            name='DocumentPassFail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_valid', models.BooleanField(default=False)),
                ('page', models.IntegerField()),
                ('failed_conditions', models.CharField(max_length=100)),
                ('document_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reasons', to='documents.document')),
            ],
        ),
        # EssayCriteria
        migrations.CreateModel(
            name='EssayCriteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(default=2025)),
                ('quater', models.IntegerField(blank=True, default=1, null=True)),
                ('content', models.TextField()),
                ('ranges', models.ManyToManyField(to='aims.evaluationrange')),
            ],
        ),
        # Evaluation
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('memo', models.TextField(blank=True, default='', null=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documents.document')),
            ],
        ),
        # EvaluationRange
        migrations.CreateModel(
            name='EvaluationRange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_value', models.IntegerField()),
                ('max_value', models.IntegerField()),
                ('penalty', models.IntegerField()),
            ],
        ),
        # Extraction
        migrations.CreateModel(
            name='Extraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='extraction', to='documents.rawdata')),
            ],
        ),
        # Summarization
        migrations.CreateModel(
            name='Summarization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, default='', null=True)),
                ('question', models.TextField(blank=True, default='', null=True)),
                ('memo', models.TextField(blank=True, default='', null=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documents.document')),
            ],
        ),
        # ValidationCriteria
        migrations.CreateModel(
            name='ValidationCriteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(max_length=100)),
                ('v_condition', models.TextField()),
            ],
        ),
    ]
