# Generated by Django 5.1.5 on 2025-01-19 11:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aims', '0001_initial'),
        ('documents', '0002_document_memo_document_state_alter_document_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='InappropriateReason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=100)),
                ('page', models.IntegerField()),
                ('x', models.IntegerField()),
                ('y', models.IntegerField()),
                ('width', models.IntegerField()),
                ('height', models.IntegerField()),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reasons', to='documents.document')),
            ],
        ),
        migrations.DeleteModel(
            name='Inappropriate_Reason',
        ),
    ]
