# Generated by Django 5.1.5 on 2025-01-29 06:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aims', '0002_initial'),
        ('documents', '0004_alter_documentation_student_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extraction',
            name='document',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='extraction', to='documents.documentation'),
        ),
    ]
