# Generated by Django 5.1.5 on 2025-01-31 12:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aims', '0003_alter_extraction_document'),
        ('documents', '0006_alter_document_document_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtractionEssay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='extraction_essay', to='documents.document')),
            ],
        ),
    ]
