# Generated by Django 5.1.5 on 2025-01-23 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aims', '0004_extraction'),
    ]

    operations = [
        migrations.CreateModel(
            name='EssayCriteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
            ],
        ),
    ]
