# Generated by Django 5.1.5 on 2025-02-07 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aims', '0006_alter_extraction_document_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='extraction',
            name='document_type',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='extraction',
            name='vector',
            field=models.TextField(blank=True, null=True),
        ),
    ]
