# Generated by Django 5.1.5 on 2025-01-23 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aims', '0007_essayrange_essaycriteria_ranges'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EssayRange',
            new_name='EvaluationRange',
        ),
    ]
