# Generated by Django 5.1.5 on 2025-02-07 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aims', '0007_extraction_document_type_extraction_vector'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentpassfail',
            name='failed_conditions',
            field=models.CharField(choices=[('none', '해당사항 없음'), ('date', '유효하지 않은 서류 발행일'), ('type', '서류 타입 검증 불일치'), ('unknown', '일치하는 이름이 명단에 없음'), ('missing_field', '필수 정보 누락'), ('unauthorized', '대상자가 아닌 신청자'), ('invalid_infomation', '정보 누락 또는 불일치')], default='none', max_length=50),
        ),
    ]
