# Generated by Django 5.1.5 on 2025-01-25 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aims', '0009_evaluation_memo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassificationCriteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classification_code', models.IntegerField()),
                ('c_condition', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ValidationCriteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(max_length=100)),
                ('v_condition', models.TextField()),
            ],
        ),
    ]
