# Generated by Django 5.1.5 on 2025-02-07 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aims', '0009_alter_documentpassfail_document_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='documentpassfail',
            old_name='failed_conditions',
            new_name='failed_condition',
        ),
    ]
