# Generated by Django 5.1.5 on 2025-01-26 05:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aims', '0010_classificationcriteria_validationcriteria'),
        ('documents', '0007_alter_document_document_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentPassFail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.IntegerField()),
                ('content', models.CharField(max_length=100)),
                ('document_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reasons', to='documents.document')),
            ],
        ),
        migrations.DeleteModel(
            name='InappropriateReason',
        ),
    ]
