# Generated by Django 5.1.5 on 2025-02-07 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aims', '0010_rename_failed_conditions_documentpassfail_failed_condition'),
    ]

    operations = [
        migrations.RenameField(
            model_name='documentpassfail',
            old_name='failed_condition',
            new_name='content',
        ),
        migrations.RemoveField(
            model_name='documentpassfail',
            name='page',
        ),
        migrations.RemoveField(
            model_name='extraction',
            name='document_type',
        ),
    ]
