# Generated by Django 5.1.5 on 2025-02-07 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aims', '0011_rename_failed_condition_documentpassfail_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='extraction',
            name='title',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
