# Generated by Django 5.1.5 on 2025-01-27 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aims', '0011_documentpassfail_delete_inappropriatereason'),
    ]

    operations = [
        migrations.AddField(
            model_name='essaycriteria',
            name='year',
            field=models.IntegerField(default=2025),
        ),
    ]
