# Generated by Django 5.1.5 on 2025-01-27 02:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aims', '0011_documentpassfail_delete_inappropriatereason'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ClassificationCriteria',
        ),
    ]
