# Generated by Django 5.1.5 on 2025-01-27 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aims', '0012_delete_classificationcriteria'),
    ]

    operations = [
        migrations.RenameField(
            model_name='documentpassfail',
            old_name='content',
            new_name='failed_conditions',
        ),
        migrations.AddField(
            model_name='documentpassfail',
            name='is_valid',
            field=models.BooleanField(default=False),
        ),
    ]
