# Generated by Django 5.1.5 on 2025-01-27 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aims', '0012_essaycriteria_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='essaycriteria',
            name='quater',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
